#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generics
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Pollens")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
	#region Extensibility Method Definitions
	partial void OnCreated();
	#endregion
		
		public DataClasses1DataContext() : 
				base(global::Generics.Properties.Settings.Default.PollensConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<nombre_polene> nombre_polenes
		{
			get
			{
				return this.GetTable<nombre_polene>();
			}
		}
		
		public System.Data.Linq.Table<polene> polenes
		{
			get
			{
				return this.GetTable<polene>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nombre_polenes")]
	public partial class nombre_polene
	{
		
		private int _Id;
		
		private string _polen;
		
		private string _nulo;
		
		private string _bajo;
		
		private string _medio;
		
		private string _alto;
		
		private string _nombre_grafico;
		
		public nombre_polene()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_polen", DbType="NVarChar(255)")]
		public string polen
		{
			get
			{
				return this._polen;
			}
			set
			{
				if ((this._polen != value))
				{
					this._polen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nulo", DbType="NChar(10)")]
		public string nulo
		{
			get
			{
				return this._nulo;
			}
			set
			{
				if ((this._nulo != value))
				{
					this._nulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bajo", DbType="NChar(10)")]
		public string bajo
		{
			get
			{
				return this._bajo;
			}
			set
			{
				if ((this._bajo != value))
				{
					this._bajo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medio", DbType="NChar(10)")]
		public string medio
		{
			get
			{
				return this._medio;
			}
			set
			{
				if ((this._medio != value))
				{
					this._medio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alto", DbType="NChar(10)")]
		public string alto
		{
			get
			{
				return this._alto;
			}
			set
			{
				if ((this._alto != value))
				{
					this._alto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_grafico", DbType="NVarChar(255)")]
		public string nombre_grafico
		{
			get
			{
				return this._nombre_grafico;
			}
			set
			{
				if ((this._nombre_grafico != value))
				{
					this._nombre_grafico = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.polenes")]
	public partial class polene
	{
		
		private System.DateTime _Fecha;
		
		private string _Ciudad;
		
		private System.Nullable<double> _Acer;
		
		private System.Nullable<double> _Alnu;
		
		private System.Nullable<double> _Apia;
		
		private System.Nullable<double> _Arte;
		
		private System.Nullable<double> _Betu;
		
		private System.Nullable<double> _Bras;
		
		private System.Nullable<double> _Cann;
		
		private System.Nullable<double> _Cast;
		
		private System.Nullable<double> _Casu;
		
		private System.Nullable<double> _Cedr;
		
		private System.Nullable<double> _Comp;
		
		private System.Nullable<double> _Cory;
		
		private System.Nullable<double> _Cupr;
		
		private System.Nullable<double> _Cype;
		
		private System.Nullable<double> _Chen;
		
		private System.Nullable<double> _Eric;
		
		private System.Nullable<double> _Frax;
		
		private System.Nullable<double> _Heli;
		
		private System.Nullable<double> _Junc;
		
		private System.Nullable<double> _Ligu;
		
		private System.Nullable<double> _Merc;
		
		private System.Nullable<double> _Mora;
		
		private System.Nullable<double> _Myrt;
		
		private System.Nullable<double> _Olea;
		
		private System.Nullable<double> _Palm;
		
		private System.Nullable<double> _Pinu;
		
		private System.Nullable<double> _Plan;
		
		private System.Nullable<double> _Plat;
		
		private System.Nullable<double> _Poac;
		
		private System.Nullable<double> _Popu;
		
		private System.Nullable<double> _Quer;
		
		private System.Nullable<double> _Rosa;
		
		private System.Nullable<double> _Rume;
		
		private System.Nullable<double> _Sali;
		
		private System.Nullable<double> _Samb;
		
		private System.Nullable<double> _Ulmu;
		
		private System.Nullable<double> _Urti;
		
		private System.Nullable<double> _Umem;
		
		private System.Nullable<double> _zygo;
		
		public polene()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this._Ciudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acer", DbType="Float")]
		public System.Nullable<double> Acer
		{
			get
			{
				return this._Acer;
			}
			set
			{
				if ((this._Acer != value))
				{
					this._Acer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alnu", DbType="Float")]
		public System.Nullable<double> Alnu
		{
			get
			{
				return this._Alnu;
			}
			set
			{
				if ((this._Alnu != value))
				{
					this._Alnu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apia", DbType="Float")]
		public System.Nullable<double> Apia
		{
			get
			{
				return this._Apia;
			}
			set
			{
				if ((this._Apia != value))
				{
					this._Apia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arte", DbType="Float")]
		public System.Nullable<double> Arte
		{
			get
			{
				return this._Arte;
			}
			set
			{
				if ((this._Arte != value))
				{
					this._Arte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Betu", DbType="Float")]
		public System.Nullable<double> Betu
		{
			get
			{
				return this._Betu;
			}
			set
			{
				if ((this._Betu != value))
				{
					this._Betu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bras", DbType="Float")]
		public System.Nullable<double> Bras
		{
			get
			{
				return this._Bras;
			}
			set
			{
				if ((this._Bras != value))
				{
					this._Bras = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cann", DbType="Float")]
		public System.Nullable<double> Cann
		{
			get
			{
				return this._Cann;
			}
			set
			{
				if ((this._Cann != value))
				{
					this._Cann = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cast", DbType="Float")]
		public System.Nullable<double> Cast
		{
			get
			{
				return this._Cast;
			}
			set
			{
				if ((this._Cast != value))
				{
					this._Cast = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Casu", DbType="Float")]
		public System.Nullable<double> Casu
		{
			get
			{
				return this._Casu;
			}
			set
			{
				if ((this._Casu != value))
				{
					this._Casu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedr", DbType="Float")]
		public System.Nullable<double> Cedr
		{
			get
			{
				return this._Cedr;
			}
			set
			{
				if ((this._Cedr != value))
				{
					this._Cedr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp", DbType="Float")]
		public System.Nullable<double> Comp
		{
			get
			{
				return this._Comp;
			}
			set
			{
				if ((this._Comp != value))
				{
					this._Comp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cory", DbType="Float")]
		public System.Nullable<double> Cory
		{
			get
			{
				return this._Cory;
			}
			set
			{
				if ((this._Cory != value))
				{
					this._Cory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cupr", DbType="Float")]
		public System.Nullable<double> Cupr
		{
			get
			{
				return this._Cupr;
			}
			set
			{
				if ((this._Cupr != value))
				{
					this._Cupr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cype", DbType="Float")]
		public System.Nullable<double> Cype
		{
			get
			{
				return this._Cype;
			}
			set
			{
				if ((this._Cype != value))
				{
					this._Cype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chen", DbType="Float")]
		public System.Nullable<double> Chen
		{
			get
			{
				return this._Chen;
			}
			set
			{
				if ((this._Chen != value))
				{
					this._Chen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eric", DbType="Float")]
		public System.Nullable<double> Eric
		{
			get
			{
				return this._Eric;
			}
			set
			{
				if ((this._Eric != value))
				{
					this._Eric = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frax", DbType="Float")]
		public System.Nullable<double> Frax
		{
			get
			{
				return this._Frax;
			}
			set
			{
				if ((this._Frax != value))
				{
					this._Frax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heli", DbType="Float")]
		public System.Nullable<double> Heli
		{
			get
			{
				return this._Heli;
			}
			set
			{
				if ((this._Heli != value))
				{
					this._Heli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Junc", DbType="Float")]
		public System.Nullable<double> Junc
		{
			get
			{
				return this._Junc;
			}
			set
			{
				if ((this._Junc != value))
				{
					this._Junc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ligu", DbType="Float")]
		public System.Nullable<double> Ligu
		{
			get
			{
				return this._Ligu;
			}
			set
			{
				if ((this._Ligu != value))
				{
					this._Ligu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Merc", DbType="Float")]
		public System.Nullable<double> Merc
		{
			get
			{
				return this._Merc;
			}
			set
			{
				if ((this._Merc != value))
				{
					this._Merc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mora", DbType="Float")]
		public System.Nullable<double> Mora
		{
			get
			{
				return this._Mora;
			}
			set
			{
				if ((this._Mora != value))
				{
					this._Mora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Myrt", DbType="Float")]
		public System.Nullable<double> Myrt
		{
			get
			{
				return this._Myrt;
			}
			set
			{
				if ((this._Myrt != value))
				{
					this._Myrt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Olea", DbType="Float")]
		public System.Nullable<double> Olea
		{
			get
			{
				return this._Olea;
			}
			set
			{
				if ((this._Olea != value))
				{
					this._Olea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Palm", DbType="Float")]
		public System.Nullable<double> Palm
		{
			get
			{
				return this._Palm;
			}
			set
			{
				if ((this._Palm != value))
				{
					this._Palm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pinu", DbType="Float")]
		public System.Nullable<double> Pinu
		{
			get
			{
				return this._Pinu;
			}
			set
			{
				if ((this._Pinu != value))
				{
					this._Pinu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Plan]", Storage="_Plan", DbType="Float")]
		public System.Nullable<double> Plan
		{
			get
			{
				return this._Plan;
			}
			set
			{
				if ((this._Plan != value))
				{
					this._Plan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plat", DbType="Float")]
		public System.Nullable<double> Plat
		{
			get
			{
				return this._Plat;
			}
			set
			{
				if ((this._Plat != value))
				{
					this._Plat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poac", DbType="Float")]
		public System.Nullable<double> Poac
		{
			get
			{
				return this._Poac;
			}
			set
			{
				if ((this._Poac != value))
				{
					this._Poac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Popu", DbType="Float")]
		public System.Nullable<double> Popu
		{
			get
			{
				return this._Popu;
			}
			set
			{
				if ((this._Popu != value))
				{
					this._Popu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quer", DbType="Float")]
		public System.Nullable<double> Quer
		{
			get
			{
				return this._Quer;
			}
			set
			{
				if ((this._Quer != value))
				{
					this._Quer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rosa", DbType="Float")]
		public System.Nullable<double> Rosa
		{
			get
			{
				return this._Rosa;
			}
			set
			{
				if ((this._Rosa != value))
				{
					this._Rosa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rume", DbType="Float")]
		public System.Nullable<double> Rume
		{
			get
			{
				return this._Rume;
			}
			set
			{
				if ((this._Rume != value))
				{
					this._Rume = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sali", DbType="Float")]
		public System.Nullable<double> Sali
		{
			get
			{
				return this._Sali;
			}
			set
			{
				if ((this._Sali != value))
				{
					this._Sali = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Samb", DbType="Float")]
		public System.Nullable<double> Samb
		{
			get
			{
				return this._Samb;
			}
			set
			{
				if ((this._Samb != value))
				{
					this._Samb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulmu", DbType="Float")]
		public System.Nullable<double> Ulmu
		{
			get
			{
				return this._Ulmu;
			}
			set
			{
				if ((this._Ulmu != value))
				{
					this._Ulmu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Urti", DbType="Float")]
		public System.Nullable<double> Urti
		{
			get
			{
				return this._Urti;
			}
			set
			{
				if ((this._Urti != value))
				{
					this._Urti = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Umem", DbType="Float")]
		public System.Nullable<double> Umem
		{
			get
			{
				return this._Umem;
			}
			set
			{
				if ((this._Umem != value))
				{
					this._Umem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zygo", DbType="Float")]
		public System.Nullable<double> zygo
		{
			get
			{
				return this._zygo;
			}
			set
			{
				if ((this._zygo != value))
				{
					this._zygo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
